### PR TITLE
Docker support

### PR DESCRIPTION
**Pull request by mishushakov**
- Added documentation entry for docker
- Added GitHub action to build docker image automatically when pushed to master branch
- Added "model" command line argument for naming models

PS. have not done any tests to the code and image yet

### CODE REVIEW

**Comment by keyth72** [comment]
Looks like a good way to implement docker, can’t wait to try it out.

**Comment by keyth72** [comment]
@mishushakov are you still working on this or is it ready for me to look at? No rush, but just wanted to make sure you weren’t waiting on me.

**Comment by mishushakov** [comment]
have to do some testing first ✌️

**Comment by mishushakov** [comment]
testing fails, i guess i choose the wrong approach
will come later with a working example

thanks

**Pull request closed without merging**
