### PR TITLE
Adds docker support

### PR DESCRIPTION
**Pull request by mishushakov**
was able to successfully build the image, mount data and train (cpu)

Screenshot 2021-02-14 at 12 20 58

### CODE REVIEW

**Comment by mishushakov** [comment]
Now also includes a GitHub action to build and publish to GitHub registry
can be pulled using:

```
docker pull ghcr.io/mishushakov/pedalnetrt:latest
```

and viewed here:
https://github.com/users/mishushakov/packages/container/package/pedalnetrt

**Comment by mishushakov** [comment]
To setup the GitHub Action

- Create a new personal access token
https://github.com/settings/tokens/new

with repo and write:packages permission

- Create a repository secret called `REGISTRY_TOKEN` with the personal access token
https://github.com/guitarml/PedalNetRT/settings/secrets/actions

**Comment by GuitarML** [comment]
That’s great! I’ve used docker but not with GitHub, so I appreciate the step by step instructions. I’ll get this merged and set up as soon as I can.

**Comment by mishushakov** [comment]
thanks for the feedback,
i haven't tried this image against a GPU, but i believe once you have the drivers it should just work
(otherwise i'd be happy to change out the base image)

once we have a Docker image in the repo others would start to base (fork) their own images on it

the PR also solves the issue with configuring environments and versions, because you can just pull the image which contains all the tools needed (for training at least)

someone could also make a cloud-based GUI, which could be using docker as a backend to train the models

**Review by GuitarML — APPROVED** [review]

**Comment by GuitarML** [comment]
@mishushakov  I'm getting a fail on the docker build action, what am I missing? I set up the token. Note that I'm also not able to see the package from your branch in the link you included. Getting a 404 not found.

**Comment by mishushakov** [comment]
go into Repo Settings > Secrets > New repository secret

then create a secret with name `REGISTRY_TOKEN` and paste your token

Screenshot 2021-02-15 at 20 47 11

**Comment by mishushakov** [comment]
then you can rerun the action from the actions tab
https://github.com/GuitarML/PedalNetRT/actions

**Comment by GuitarML** [comment]
I had put in the registry token as a repository secret, and I just double checked it and reran the action but still getting a fail. Is it properly building on your branch? I wasn't able to see  the docker container in the link you posted.

**Comment by mishushakov** [comment]
yeap, all works on my side

Screenshot 2021-02-15 at 21 31 49
Screenshot 2021-02-15 at 21 31 18

maybe you don't have access to the GitHub registry yet

try to go to profile > feature preview and enable improved container support

Screenshot 2021-02-15 at 21 32 35
Screenshot 2021-02-15 at 21 33 12

if you don't see it, i could ask someone at GitHub to give you access :)

**Comment by mishushakov** [comment]
that seems to be the case
please see the action log

https://github.com/GuitarML/PedalNetRT/runs/1905997090

**Comment by mishushakov** [comment]
also in package settings don't forget to make it public
(sorry you have to jump through so many hoops)

Screenshot 2021-02-15 at 22 16 34

**Comment by GuitarML** [comment]
Success! Looks like a really big container, currently downloading about 2.5 GB, is that just from the PyTorch image?

**Comment by mishushakov** [comment]
that's right, the pytorch image takes 2.3GB

you can use something like dive to see what's inside
https://github.com/wagoodman/dive

i'll check if the size reduces if i'd be "cooking" the image myself instead of relying on pytorch - especially considering all the cuda stuff has to be working

**Pull request merged**
